# ========== 启动配置 ==========
[runtime.raw]
config = [
    { app = "client_code_1", background = true },
    #{ app = "client_code_2", background = true },
    { app = "client_conv_1", background = false },
    #{ app = "client_conv_2", background = false },
]

# ======= Shared variables ========
# can be ingested from outside to avoid hard coding
# NOTE: RHS can only expand parameters defined outside ${var-name}
[variables]
model_path = "${model-path}"
blitzdir = "${work-dir}"
tokenizer_path = "${model-path}/tokenizer.json"
vllm_executable = "${venv-path}/bin/vllm serve"
client_executable = "${work-dir}/target/release/client"
base_vllm_port = 59180
dataset_dir = "/nvme/lmetric/datasets"
log_dir = "${log-dir}"
output_dir = "${output-dir}"
conv_trace_name = "AzureLLMInferenceTrace_conv.csv"
code_trace_name = "AzureLLMInferenceTrace_code.csv"


# ======= Immutable template ========
[app.client_template]
executable = ["${client_executable}"]
extra_args = ["--replay-mode"]

[app.client_template.macro_rules]
"--tokenizer" = "tokenizer"
"--endpoint" = "endpoint"
"--protocol" = "protocol"
"--scale-factor" = "scale_factor"
"--dataset-type" = "dataset_type"
"--dataset-path" = "dataset_path"
"--time-in-secs" = "time_in_secs"
"--truncate" = "truncate"
"--output-path" = "output_path"

# ========== 具体客户端实例 ==========
[app.client_code_1]
inherit = "client_template"
config.tokenizer = "${tokenizer_path}"
config.endpoint = "http://localhost:58009/generate"
config.protocol = "st"
config.scale_factor = 2.0
config.dataset_type = "azure"
config.dataset_path = "${dataset_dir}/${code_trace_name}"
config.time_in_secs = 120
config.truncate = 16000
config.output_path = "${output_dir}/client_code_1.jsonl"

[app.client_code_2]
inherit = "client_template"
config.tokenizer = "${tokenizer_path}"
config.endpoint = "http://localhost:58009/generate"
config.protocol = "st"
config.scale_factor = 2.0
config.dataset_type = "azure"
config.dataset_path = "${dataset_dir}/${code_trace_name}"
config.time_in_secs = 120
config.truncate = 16000
config.output_path = "${output_dir}/client_code_2.jsonl"

[app.client_conv_1]
inherit = "client_template"
config.tokenizer = "${tokenizer_path}"
config.endpoint = "http://localhost:58009/generate"
config.protocol = "st"
config.scale_factor = 1.0
config.dataset_type = "azure"
config.dataset_path = "${dataset_dir}/${conv_trace_name}"
config.time_in_secs = 120
config.truncate = 16000
config.output_path = "${output_dir}/client_conv_1.jsonl"

[app.client_conv_2]
inherit = "client_template"
config.tokenizer = "${tokenizer_path}"
config.endpoint = "http://localhost:58009/generate"
config.protocol = "st"
config.scale_factor = 2.0
config.dataset_type = "azure"
config.dataset_path = "${dataset_dir}/${conv_trace_name}"
config.time_in_secs = 120
config.truncate = 16000
config.output_path = "${output_dir}/client_conv_2.jsonl"
