# ========== 启动配置 ==========
[runtime.raw]
config = [
    { app = "vllm_template", envs = { CUDA_VISIBLE_DEVICES = "0", TORCH_CUDA_ARCH_LIST = "9.0" }, background = true, base_port=59180, port_offset = 0 },
    { app = "vllm_template", envs = { CUDA_VISIBLE_DEVICES = "1", TORCH_CUDA_ARCH_LIST = "9.0" }, background = true, base_port=59180, port_offset = 1 },
    { app = "vllm_template", envs = { CUDA_VISIBLE_DEVICES = "2", TORCH_CUDA_ARCH_LIST = "9.0" }, background = true, base_port=59180, port_offset = 2 },
    { app = "vllm_template", envs = { CUDA_VISIBLE_DEVICES = "3", TORCH_CUDA_ARCH_LIST = "9.0" }, background = true,  base_port=59180, port_offset = 3 },
    { app = "vllm_template", envs = { CUDA_VISIBLE_DEVICES = "4", TORCH_CUDA_ARCH_LIST = "9.0" }, background = true, base_port=59180, port_offset = 4 },
    { app = "vllm_template", envs = { CUDA_VISIBLE_DEVICES = "5", TORCH_CUDA_ARCH_LIST = "9.0" }, background = true, base_port=59180,port_offset = 5 },
    { app = "vllm_template", envs = { CUDA_VISIBLE_DEVICES = "6", TORCH_CUDA_ARCH_LIST = "9.0" }, background = true, base_port=59180,port_offset = 6 },
    { app = "vllm_template", envs = { CUDA_VISIBLE_DEVICES = "7", TORCH_CUDA_ARCH_LIST = "9.0" }, background = false, base_port=59180,port_offset = 7 },
]

# ======= Shared variables ========
# can be ingested from outside to avoid hard coding
# NOTE: RHS can only expand parameters defined outside ${var-name}
[variables]
model_path = "${model-path}"
blitzdir = "${work-dir}"
tokenizer_path = "${model-path}/tokenizer.json"
vllm_executable = "${venv-path}/bin/vllm serve"
client_executable = "${work-dir}/target/release/client"
base_vllm_port = 59180
dataset_dir = "/nvme/lmetric/datasets"
log_dir = "${log-dir}"
output_dir = "${output-dir}"

# ========== 模板定义 ==========
#  "--base-port", "${base_vllm_port}",

[app.vllm_template]
executable = ["${vllm_executable}"]
extra_args = [
    "${model_path}",
    "--no-enable-prefix-caching",
    "--max-num-batched-tokens", "1024",
    "--port", "${port}",
    "> ${log_file} 2>&1"
]
