
[runtime]

[runtime.mpi]
executable = ["mpirun"]
extra_args = ["--allow-run-as-root"]
# (intra node)
macro_rules = { "-n" = "start_num"}
# (inter node)
# macro_rules = {"--map-by" = "map_by", "--mca" = "mca" }


[[runtime.mpi.config]]
envs = { CUDA_VISIBLE_DEVICES = "0,1,2,3,4,5,6,7", RUST_BACKTRACE = "full", LOG_LEVEL = "info" }
app = "server"
background = true
# app will block main proc until keyword appears
block_keyword = "Start gRPC server on"

# (intra node)
start_num = 8
# (inter node)
# inter_node = true
# start_num = 16
# hosts = {g0008 = 8, g0009 = 8}
# map_by = "slot"
# mca = "btl_tcp_if_include=eth0"



[runtime.raw]

[[runtime.raw.config]]
envs = { CUDA_VISIBLE_DEVICES = "0,1,2,3,4,5,6,7", RUST_BACKTRACE = "full", LOG_LEVEL = "info" }
app = "router"
background = true

[[runtime.raw.config]]
envs = { CUDA_VISIBLE_DEVICES = "0,1,2,3,4,5,6,7", RUST_BACKTRACE = "full", LOG_LEVEL = "info" }
app = "client"
background = false


[app]

[app.server]
executable = [
    "/nvme/ly/blitz-infer-pack/build/release/bin/run_server_disaggregative",
]
extra_args = []


[app.server.macro_rules]
"-T" = "tokenizer"
"-V" = "v"
"--host" = "host"
"--port" = "port"
"--model-path" = "model_path"
"--model-name" = "model"
"-P" = "precision"
"--config" = "cfg_path"
"--num-total-blocks" = "block_num"
"-TP" = "tp_size"
"--ibv-rate" = "ibv_rate"


[app.server.config]
tokenizer = "/nvme/huggingface/hub/models--LLM-Research--Meta-Llama-3.1-8B-Instruct/tokenizer.json"
v = ""
host = "localhost"
port = "50061"
model_path = ""
model = "llama3_8b"
precision = "fp16"
cfg_path = "/nvme/ly/blitz-infer-pack/exps/blitz-run/configs/config-server.json"
block_num = 5000
tp_size = 1
ibv_rate = 0


[app.router]
executable = ["/nvme/ly/blitz-infer-pack/target/release/router_v2"]
extra_args = ["--use-tokenizer"]


[app.router.macro_rules]
"--hostname" = "hostname"
"--port" = "port"
"--deployment" = "deploy"
"--tokenizer-name" = "tokenizer"
"--model-name" = "model"
"--model-path" = "model_path"
"--parameter-size" = "param_size"
"--client-config" = "cli_stub_cfg"
"--deployment-config-path" = "deploy_cfg"
"--log-path" = "log_path"
"--max-input-length" = "context_length"
"--max-total-tokens" = "total_tokens"
"--max-concurrent-requests" = "concurrent_req"
"--tokens-prefilled-per-sec" = "prefill_thpt"
"--tokens-transferred-per-sec" = "network_thpt"
"--max-blocks-per-replica" = "block_num"
"--max-prefill-num" = "max_prefill"
"--max-decode-num" = "max_decode"
"--min-prefill-num" = "min_prefill"
"--min-decode-num" = "min_decode"
"--prefill-lower-bound" = "prefill_scale_down_threshold"
"--prefill-upper-bound" = "prefill_scale_out_threshold"
"--decode-lower-bound" = "decode_scale_down_threshold"
"--decode-upper-bound" = "decode_scale_up_threshold"
"--migration-lower-bound" = "migrate_scale_down_threshold"
"--migration-upper-bound" = "migrate_scale_up_threshold"
"--scale-down-threshold-millis" = "time_to_leave"
"--num-hidden-layers" = "model_layers"
"--num-gpus-per-node" = "gpu_num_per_node"
"--mock-load-millis" = "mock_load_time"
"--mock-transfer-millis" = "mock_transfer_time"
"--tensor-parallel-size" = "tp_size"


[app.router.config]
hostname = "localhost"
port = "11236"
deploy = "disaggregation"
model = "llama3-8b"
model_path = "/nvme/huggingface/hub/models--LLM-Research--Meta-Llama-3.1-8B-Instruct"
tokenizer = "/nvme/huggingface/hub/models--LLM-Research--Meta-Llama-3.1-8B-Instruct"
param_size = 16
cli_stub_cfg = "/nvme/ly/blitz-infer-pack/exps/blitz-run/configs/config-stubs.json"
deploy_cfg = "/nvme/ly/blitz-infer-pack/exps/blitz-run/configs/config-router.json"
log_path = "/tmp/router.log"
context_length = 4090
total_tokens = 4096
concurrent_req = 4096
prefill_thpt = 13000
network_thpt = 30000
block_num = 8000
max_prefill = 7
max_decode = 7
min_prefill = 1
min_decode = 1
prefill_scale_down_threshold = 0.3
prefill_scale_out_threshold = 0.6
decode_scale_down_threshold = 0.66
decode_scale_up_threshold = 0.9
migrate_scale_down_threshold = 0.2
migrate_scale_up_threshold = 0.4
time_to_leave = 1000
model_layers = 32
gpu_num_per_node = 8
mock_load_time = 0
mock_transfer_time = 0
tp_size = 1


[app.client]
executable = ["/nvme/ly/blitz-infer-pack/target/release/client"]
extra_args = ["--replay-mode"]


[app.client.macro_rules]
"--tokenizer" = "tokenizer"
"--endpoint" = "endpoint"
"--protocol" = "protocol"
"--scale-factor" = "scale_factor"
"--dataset-type" = "dataset_type"
"--dataset-path" = "dataset_path"
"--time-in-secs" = "time_in_secs"
"--truncate" = "truncate"
"--output-path" = "output_path"


[app.client.config]
tokenizer = "/nvme/huggingface/hub/models--LLM-Research--Meta-Llama-3.1-8B-Instruct/tokenizer.json"
endpoint = "http://localhost:11236/generate"
protocol = "st"
scale_factor = 0.6
dataset_type = "processed"
dataset_path = "/nvme/ly/blitz-infer-pack/dataset/azure-conv-percentage-20.csv"
time_in_secs = 10
truncate = 4095
output_path = "/tmp/client.jsonl"
