
# ssh run one http server and client
# python runner.py --toml <path/to/toml> --rt raw/ssh
# rt is required in this case since we've defined two running methods


[runtime]

[runtime.raw]
[[runtime.raw.config]]
app = "pong"
background = true


[[runtime.raw.config]]
app = "ping"
background = false



[runtime.ssh]
executable = ["ssh"]
macro_rules = {}
extra_args = ["-o", "StrictHostKeyChecking=no"]


[[runtime.ssh.config]]
app = "pong"
remote_user = "ly"
remote_host = "127.0.0.1"
background = true


[[runtime.ssh.config]]
app = "ping"
remote_user = "ly"
remote_host = "127.0.0.1"
background = false

#----------------------------------------------------------------------------

[app]


[app.pong]
executable = ["python3", "/nvme/ly/blitz-scale/scripts/batchv3/pong.py"]
extra_args = []

[app.pong.macro_rules]
"--port" = "port"
"--message" = "message"


[app.pong.config]
port = 8888
message = "pong"

#----------------------------------

[app.ping]
executable = ["python3", "/nvme/ly/blitz-scale/scripts/batchv3/ping.py"]
extra_args = []

[app.ping.macro_rules]
"--ip" = "ip"
"--port" = "port"


[app.ping.config]
ip = "127.0.0.1"
port = "8888"
