# ========== 启动配置 ==========
[runtime.raw]
config = [
    # 动态生成 vLLM 实例 (vllm1-vllm8)
    { app = "vllm_template", envs = { CUDA_VISIBLE_DEVICES = "0", TORCH_CUDA_ARCH_LIST = "9.0", VLLM_ATTENTION_BACKEND = "FLASHINFER" }, background = true, base_port = 59180, port_offset = 0 },
    { app = "vllm_template", envs = { CUDA_VISIBLE_DEVICES = "1", TORCH_CUDA_ARCH_LIST = "9.0", VLLM_ATTENTION_BACKEND = "FLASHINFER" }, background = true, base_port = 59180, port_offset = 1 },
    { app = "vllm_template", envs = { CUDA_VISIBLE_DEVICES = "2", TORCH_CUDA_ARCH_LIST = "9.0", VLLM_ATTENTION_BACKEND = "FLASHINFER" }, background = true, base_port = 59180, port_offset = 2 },
    { app = "vllm_template", envs = { CUDA_VISIBLE_DEVICES = "3", TORCH_CUDA_ARCH_LIST = "9.0", VLLM_ATTENTION_BACKEND = "FLASHINFER" }, background = true, base_port = 59180, port_offset = 3 },
    { app = "vllm_template", envs = { CUDA_VISIBLE_DEVICES = "4", TORCH_CUDA_ARCH_LIST = "9.0", VLLM_ATTENTION_BACKEND = "FLASHINFER" }, background = true, base_port = 59180, port_offset = 4 },
    { app = "vllm_template", envs = { CUDA_VISIBLE_DEVICES = "5", TORCH_CUDA_ARCH_LIST = "9.0", VLLM_ATTENTION_BACKEND = "FLASHINFER" }, background = false, base_port = 59180, port_offset = 5 },

]

# 公共变量（方便统一修改）
[variables]
model_path = "/nvme/models/Meta-Llama-3-8B-Instruct/"
vllm_executable = "/nvme/zkx/modified-vllm/myenv/bin/vllm serve"
base_vllm_port = 59180

# ========== 模板定义 ==========
#  "--base-port", "${base_vllm_port}",

[app.vllm_template]
executable = ["${vllm_executable}"]
extra_args = [
    "${model_path}",
    "--no-enable-prefix-caching",
    "--max-num-batched-tokens",
    "1024",
    "--port",
    "${port}",
    "--enforce-eager",
    # "--use_cudagraph",
    "> ${log_file} 2>&1",
]
