# ========== 启动配置 ==========
[runtime.raw]
config = [
    # 动态生成 vLLM 实例 (vllm1-vllm8)
    { app = "vllm_template", envs = { "PYTHONPATH" = "/nvme/zkx/Modified_vidur" }, background = true, base_port = 8080, port_offset = 0 },
    { app = "vllm_template", envs = { "PYTHONPATH" = "/nvme/zkx/Modified_vidur" }, background = true, base_port = 8080, port_offset = 1 },
    { app = "vllm_template", envs = { "PYTHONPATH" = "/nvme/zkx/Modified_vidur" }, background = true, base_port = 8080, port_offset = 2 },
    { app = "vllm_template", envs = { "PYTHONPATH" = "/nvme/zkx/Modified_vidur" }, background = true, base_port = 8080, port_offset = 3 },
    { app = "vllm_template", envs = { "PYTHONPATH" = "/nvme/zkx/Modified_vidur" }, background = true, base_port = 8080, port_offset = 4 },
    { app = "vllm_template", envs = { "PYTHONPATH" = "/nvme/zkx/Modified_vidur" }, background = false, base_port = 8080, port_offset = 5 },
    # { app = "vllm_template", envs = { "PYTHONPATH" = "/nvme/zkx/Modified_vidur" }, background = false, base_port = 8080, port_offset = 6 },
]

# 公共变量（方便统一修改）
[variables]
simulator_executable = "cd /nvme/zkx/Modified_vidur && /root/miniconda3/envs/vidur/bin/python -m vidur.main"
client_executable = "/nvme/zkx/blitz-infer-pack/target/release/client"
base_vllm_port = 59180

# ========== 模板定义 ==========
#  "--base-port", "${base_vllm_port}",

[app.vllm_template]
executable = ["${simulator_executable}"]
extra_args = [
    "--replica_config_device",
    "h20",
    "--replica_config_model_name",
    "meta-llama/Meta-Llama-3-8B",
    "--cluster_config_num_replicas",
    "1",
    "--replica_config_tensor_parallel_size",
    "1",
    "--replica_config_num_pipeline_stages",
    "1",
    "--request_generator_config_type",
    "synthetic",
    "--synthetic_request_generator_config_num_requests",
    "2048",
    "--length_generator_config_type",
    "trace",
    "--trace_request_length_generator_config_max_tokens",
    "16384",
    "--trace_request_length_generator_config_trace_file",
    "./data/processed_traces/splitwise_conv.csv",
    "--interval_generator_config_type",
    "poisson",
    "--poisson_request_interval_generator_config_qps",
    "2",
    "--replica_scheduler_config_type",
    "vllm",
    "--random_forrest_execution_time_predictor_config_prediction_max_prefill_chunk_size",
    "1024",
    "--random_forrest_execution_time_predictor_config_prediction_max_batch_size",
    "1024",
    "--random_forrest_execution_time_predictor_config_prediction_max_tokens_per_request",
    "16384",
    "--port",
    "${port}",
    "> ${log_file} 2>&1",
]
